pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "approved-reviews-by=@broadlume/active-tatami-contributors"
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
